### ISSUE TITLE
Nucleus segmentation of WSI in PNG results in ValueError: MPP is None. Cannot determine scale in terms of MPP.

### ISSUE THREAD

**Issue by Calebium** [TissueImageAnalytics/tiatoolbox#508]
- TIA Toolbox version: 1.3.0
- Python version: 3.7
- Operating System: Cent OS

### Description

Calling NucleusInstanceSegmentor.predict() with H&E (RGB, PNG) whole-slide image files result in the following error:

  ValueError: MPP is None. Cannot determine scale in terms of MPP.

### What I Did

I used the IOSegmentorConfig to specify the mpp of my inputs and outputs (H&E images in RGB and PNG format), but when I try to perform the segmentation I get an error saying that the MPP is None. Since PNG files don't contain any metadata info, I was hoping that by specifying it in IOSegmentorConfig will provide that info.

```
objIOConfig = IOSegmentorConfig(
    input_resolutions=[
        {'units': 'mpp', 'resolution': 0.325}, 
    ],
    output_resolutions=[
        {'units': 'mpp', 'resolution': 0.325}, 
    ],
    margin=128,
    tile_shape=[1024, 1024],
    patch_input_shape=(256, 256),
    patch_output_shape=(256, 256),
    stride_shape=(164, 164),
    save_resolution={'units': 'mpp', 'resolution': 0.325}
)

# Instantiate the nucleus instance segmentor
objInstSegmentor = NucleusInstanceSegmentor(
    pretrained_model="hovernet_fast-pannuke", 
    num_loader_workers=4, 
    num_postproc_workers=4, 
    batch_size=8, 
    auto_generate_mask=False, 
    verbose=False, 
)

# WSI prediction (if ON_GPU=False, this part will take more than a couple of hours to process)
wsi_output = objInstSegmentor.predict(
    ['TestSet_ROI_6291_wsi_he.png'], 
    ioconfig=objIOConfig, 
    masks=None, 
    save_dir=f'./WSITest/', 
    mode="wsi", 
    on_gpu=ON_GPU, 
    crash_on_exception=True, 
)
```

The error that I encountered in more detail:

<img width="1504" alt="Screen Shot 2022-11-04 at 5 19 00 PM" src="https://user-images.githubusercontent.com/8196285/200092128-1c6ab7cc-efa5-4500-afee-19a9358c3060.png">

<img width="1501" alt="Screen Shot 2022-11-04 at 5 19 11 PM" src="https://user-images.githubusercontent.com/8196285/200092117-c632ef99-19d9-4354-a9ef-fa137c2293dc.png">

Thank you!

Caleb

**Comment by shaneahmed** [comment]
Hi @Calebium,

As png files do not contain meta data for mpp. This throws an error. You can manually specify mpp values while reading the image using WSIReader to avoid this error.

**Comment by Calebium** [comment]
Hi,

I realize that we can specify the mpp parameter in the WSIReader. Is there a similar way to do that with the NucleusInstanceSegmentor? I have tried to do that through the IOSegmentorConfig object but that didn't seem to help. Thanks!

Caleb

**Comment by shaneahmed** [comment]
We are looking into how we can integrate this. One way could be to pass as kwargs or we can allow passing WSIReader objects as well. We will update this issue once we start working on this.

**Comment by Calebium** [comment]
Is there a quick workaround that I can temporarily to get around this issue? I can make a local change of the code if necessary. Thanks!

**Comment by shaneahmed** [comment]
A quick work around would be to clone the repo and add mpp here. I haven't tested this but it should work.

https://github.com/TissueImageAnalytics/tiatoolbox/blob/6553b62334f7c2ff524ec192f487f26c54286f91/tiatoolbox/models/engine/semantic_segmentor.py#L672

**Comment by mostafajahanifar** [comment]
Dear @Calebium 

As you are trying to make predictions on image tiles, it is better to call the `predict` method in `tile` mode instead of `mode=wsi`. If you specify the `mode` to be `wsi`, TIAToolbox requires the input to be a WSI structured file with metadata information.

Therefore, an easy solution to your problem is to set the `mode` in the last method call to `tile`:
```
wsi_output = objInstSegmentor.predict(
    ['TestSet_ROI_6291_wsi_he.png'], 
    ioconfig=objIOConfig, 
    masks=None, 
    save_dir=f'./WSITest/', 
    mode="tile",  # NOT `wsi`
    on_gpu=ON_GPU, 
    crash_on_exception=True, 
)
```

[Extra Suggestion]
I noticed you are trying to set the input resolution to "mpp resolution: 0.325" for your input. You should know, this `IOConfig` is to set the config of image reading with respect to the trained model, not the test data! So, whatever resolution the data has been captured with, if you want to get the best results using TIAToolbox's HoVerNet, input images to the algorithm should be in "mpp resolution: 0.25".
Now, if your images are saved in a resolution that is different from the images used in the HoVerNet model training, I would suggest you resize the images to "mpp resolution: 0.255" before you process them in order to achieve the best segmentation resolution. However, even without resizing you should obtain acceptable results.

**Comment by Calebium** [comment]
Thank you for your suggestions. If I call the predict method in tile mode with a whole slide image, how is it treated differently than calling with the same image in wsi mode? Thanks!

**Comment by shaneahmed** [comment]
If you use "tile" mode then,
https://github.com/TissueImageAnalytics/tiatoolbox/blob/b7fdf50f0309fe1d893c1d5afcbf558b4682c280/tiatoolbox/models/engine/semantic_segmentor.py#L324-L329

You can manually specify mpp however here https://github.com/TissueImageAnalytics/tiatoolbox/blob/b7fdf50f0309fe1d893c1d5afcbf558b4682c280/tiatoolbox/models/engine/semantic_segmentor.py#L353-L356

**Comment by mostafajahanifar** [comment]
> Thank you for your suggestions. If I call the predict method in tile mode with a whole slide image, how is it treated differently than calling with the same image in wsi mode? Thanks!

If you use `tile` mode, TIAToolbox assumes the input is a plain image. Therefore, if the input is a path to a png image, the toolbox tries to read it with a simple `cv2.imread` function (which is not capable of reading WSIs) and append a predefined standard metadata to it. Therefore, reading a WSI in tile mode will raise an external exception (error). However, if you read a png in the WSI mode, because if WSI mode toolbox assumes there is some metadata associated with the input it would not change the metadata (does not append predefined standard metadata to WSI) and instead throws warnings that metadata is missing and won't be able to operations that are metadata dependant (such as reading from a specific mpp).
